version: "3.7"

services:
  pulsar:
    image: apachepulsar/pulsar:2.8.1
    container_name: pulsar_container
    command: bin/pulsar standalone
    ports:
      - "8081:8080"
      - "6650:6650"
    restart: unless-stopped
    volumes:
      - ./data/pulsardata:/pulsar/data
      # - ./conf/pulsarconf:/pulsar/conf
    networks:
      messagequeue:
        aliases:
          - pulsar

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.2.0
    container_name: pulsar_manager_container
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      messagequeue:

  typesense:
    image: typesense/typesense:0.21.0
    container_name: typesense_container
    restart: unless-stopped
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: "/data"
    depends_on:
      - pulsar
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense-data:/data

networks:
  messagequeue:
    name: messagequeue
