version: '3'

services:

  redis:
    image: eqalpha/keydb:latest
    restart: unless-stopped
    container_name: redis_container
    ports:
      - "6300:6379"
    # volumes:
    #   - ./redis.conf:/etc/redis/redis.conf 
    #   - ./data:/data      
    command: keydb-server --requirepass keypassword
    privileged: true