[default]
address = "0.0.0.0"

[debug.databases.pgdb]
# postgres://username:password@host:port/dbname
url = "postgres://postgres:postgres@127.0.0.1:5432/pgdb"

[debug.databases.keydb]
url = "redis://:keypassword@127.0.0.1:6300"

[debug.databases.pulsar-mq]
url = "pulsar://127.0.0.1:6650"
