//! SeaORM Entity. Generated by sea-orm-codegen 0.3.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "content_post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub post_id: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub burrow_id: i64,
    pub create_time: DateTimeWithTimeZone,
    pub last_modify_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub section: String,
    #[sea_orm(column_type = "Text")]
    pub tag: String,
    pub post_len: i32,
    pub post_state: i16,
    pub like_num: i32,
    pub collection_num: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            _ => panic!("No RelationDef"),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
