//! SeaORM Entity. Generated by sea-orm-codegen 0.3.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "content_subject")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub post_id: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub author: String,
    pub anonymous: bool,
    pub created_time: DateTimeWithTimeZone,
    pub modified_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub section: String,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())", nullable)]
    pub tag: Option<String>,
    pub post_len: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            _ => panic!("No RelationDef"),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
