//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

pub mod prelude;

pub mod burrow;
pub mod content_post;
pub mod content_reply;
pub mod image;
pub mod user;
pub mod user_collection;
pub mod user_follow;
pub mod user_like;
pub mod user_status;
